version: 2

models:
  - name: my_first_model
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: my_third_model
    columns:
      - name: id
        tests:
          - unique